const ErrorCodes = {
  PASSPORT_UNAUTHORIZED_ERROR_CODE: 1,
  INVALID_CREDENTIALS_ERROR_CODE: 2,
  ACCOUNT_LOCKED_ERROR_CODE: 3,
  INVALID_NEW_PASSWORD_ERROR_CODE: 4,
  DUPLICATED_USER_ERROR_CODE: 5,
  USER_NOT_FOUND_ERROR_CODE: 6,
  SERVICE_ITEM_TEMPLATE_NOT_FOUND_ERROR_CODE: 7,
  VEHICLE_NOT_FOUND_ERROR_CODE: 8,
  DUPLICATED_CARPLATE_NUMBER_ERROR_CODE: 9,
  CLIENT_NOT_FOUND_ERROR_CODE: 10,
  SERVICE_NOT_FOUND_ERROR_CODE: 11,
  JOB_NOT_FOUND_ERROR_CODE: 12,
  ENTITY_NOT_FOUND_ERROR_CODE: 13,
  EXCEEDED_LICENSE_USAGE_ERROR_CODE: 55,
  INSUFFICIENT_PERMISSION_ERROR_CODE: 66,
  INPUT_VALIDATION_ERROR_CODE: 77,
  MALFORMED_JSON_ERROR_CODE: 88,
  RUNTIME_ERROR_CODE: 99
};

export default ErrorCodes;
